name: pub_dev
author: Dart Team <misc@dartlang.org>
description: The pub.dartlang.org website.
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  _popularity:
    path: ../pkg/_popularity
  neat_cache: ^1.0.0
  appengine: '^0.13.0'
  args: '^2.0.0'
  basics: ^0.6.0
  client_data:
    path: ../pkg/client_data
  convert: '^3.0.0'
  crypto: '^3.0.0'
  fake_gcloud:
    path: ../pkg/fake_gcloud
  gcloud: '^0.8.0'
  googleapis: '^3.0.0'
  googleapis_auth: ^1.1.0
  html: ^0.15.0
  http: ^0.13.0
  http_parser: ^3.0.0
  intl: '^0.17.0'
  json_annotation: '^3.0.0'
  logging: '>=0.9.3 <2.0.0'
  markdown: ^4.0.0
  meta: ^1.1.2
  mime: '>=0.9.3 <2.0.0'
  mustache: ^1.0.0
  neat_periodic_task: ^2.0.0
  path: '^1.8.0'
  pool: '^1.5.0'
  pub_dartdoc_data:
    path: ../pkg/pub_dartdoc_data
  pub_package_reader:
    path: ../pkg/pub_package_reader
  pub_semver: '^2.0.0'
  pubspec_parse: ^1.0.0
  shelf: '^0.7.9'
  shelf_router: ^0.7.4
  stack_trace: ^1.10.0
  stream_transform: ^2.0.0
  watcher: ^1.0.0
  yaml: '^3.0.0'
  # pana version to be pinned
  pana: '0.18.2'
  # 3rd-party packages with pinned versions
  buffer: '1.1.0'
  mailer: '5.0.0'
  sanitize_html: ^2.0.0
  ulid: '2.0.0'
  tar: '0.4.0'
  http_retry: '0.2.0'
  api_builder:
    path: ../pkg/api_builder

dev_dependencies:
  build_runner: '^1.0.0'
  build_verify: ^1.1.1
  coverage: any # test already depends on it
  json_serializable: '^3.0.0'
  pub_validations:
    path: ../pkg/pub_validations
  shelf_router_generator: ^0.7.2+3
  source_gen: '^0.9.0'
  test: ^1.16.5
  xml: ^5.0.0

dependency_overrides:
  analyzer: ^1.0.0 # build tools
  checked_yaml: ^2.0.0 #build_runner
  convert: ^3.0.0 # neat_cache
  http_parser: ^3.0.0 # shelf
  io: ^0.3.0 # build_runner
  json_annotation: '^3.0.0' # neat_periodic_task
  logging: ^1.0.0 # several dependencies
  pubspec_parse: ^1.0.0 # build_runner
